[pytest]
addopts = -v -s --junitxml=reports/junit.xml --html=reports/test_report.html --self-contained-html --css=reports/modern_report.css --alluredir=reports/allure-results
testpaths = tests features
norecursedirs = venv .venv .auth
filterwarnings =
    ignore::DeprecationWarning
markers =
    smoke: mark test as smoke test
    regression: mark test as regression test
    serial: run sequentially
    order(index): set test execution order index
    authenticated: mark test as requiring an authenticated dashboard/session
    payment: mark payment-related tests (should be run serially)
    invalid: BDD tag for invalid login
    empty: BDD tag for empty login