import pytest
from playwright.sync_api import expect
from pages.login.login_page import LoginPage
from utils.config import Config

def test_portal_login_and_select_app_and_logout(page):
    """
    [Positive] Validates end-to-end user login to NJDOT portal, selection of
    TEST Outdoor Advertising application, and logout.
    """
    # 1. Initialize Page Objects
    login_page = LoginPage(page)
    
    # 2. Navigate to Login Page
    login_page.load(Config.LOGIN_URL)
    
    # 3. Read valid credentials
    import json
    login_data_path = Config.PROJECT_ROOT / "testdata" / "login_data.json"
    with open(login_data_path) as f:
        valid_user = json.load(f)["valid_users"][0]
        
    # 4. Perform Login
    login_page.login(email=valid_user["email"], password=valid_user["password"])
    
    # 5. Select Outdoor Advertising Application
    login_page.select_outdoor_advertising()
    
    # 6. Verify that "TEST Outdoor Advertising" link is visible
    expect(login_page.outdoor_advertising_link).to_be_visible()
    
    # 7. Perform Logout
    login_page.logout()


def test_login_empty_credentials(page):
    """
    [Negative] Verifies validation errors when submitting empty credentials.
    """
    # 1. Initialize Page Objects
    login_page = LoginPage(page)
    
    # 2. Navigate to Login Page
    login_page.load(Config.LOGIN_URL)
    
    # 3. Perform Login without credentials
    login_page.login(email="", password="")
    
    # 4. Assert validation errors are visible
    expect(login_page.email_mandatory_error).to_be_visible()
    expect(login_page.password_mandatory_error).to_be_visible()


def test_login_invalid_password(page, faker):
    """
    [Negative] Verifies validation error dialog for a valid email with an incorrect password.
    """
    # 1. Initialize Page Objects
    login_page = LoginPage(page)
    
    # 2. Navigate to Login Page
    login_page.load(Config.LOGIN_URL)
    
    # 3. Perform Login with invalid password generated by Faker
    random_password = faker.password(length=12, special_chars=True, digits=True, upper_case=True, lower_case=True)
    login_page.login(email="sprabhu@bemsys.com", password=random_password)
    
    # 4. Assert invalid login dialog is visible
    expect(login_page.invalid_credentials_error).to_be_visible()
    
    # 5. Dismiss alert dialog
    login_page.dismiss_alert()


def test_login_invalid_email(page, faker):
    """
    [Negative] Verifies validation error dialog for an invalid email with a valid password.
    """
    # 1. Initialize Page Objects
    login_page = LoginPage(page)
    
    # 2. Navigate to Login Page
    login_page.load(Config.LOGIN_URL)
    
    # 3. Perform Login with invalid email format generated by Faker
    # Generating an invalid domain format (e.g. test@gmail without .com)
    invalid_email = f"{faker.user_name()}@gmail"
    login_page.login(email=invalid_email, password="Security@#")
    
    # 4. Assert invalid login dialog is visible
    expect(login_page.invalid_credentials_error).to_be_visible()
    
    # 5. Dismiss alert dialog
    login_page.dismiss_alert()
