from pages.base_page import BasePage
from utils.config import Config

class LoginPage(BasePage):
    def __init__(self, page):
        super().__init__(page)
        # Locators specifically generated by Playwright Codegen
        self.email_input = page.get_by_role("textbox", name="Email")
        self.password_input = page.get_by_role("textbox", name="Password")
        self.login_button = page.get_by_role("button", name="Login")
        self.spin_button = page.get_by_role("spinbutton")
        
        # Fallback locator for catching error messages during invalid login attempts
        self.error_message = page.locator(".toast-message, .validation-summary-errors, .error-message, text='Invalid'")

    def load(self, url: str):
        self.page.goto(url, timeout=Config.TIMEOUT, wait_until="domcontentloaded")

    def login(self, email: str, password: str, pin: str = "11"):
        # Perform Login steps as per codegen
        if email:
            self.email_input.click()
            self.email_input.fill(email)
        
        if password:
            self.password_input.click()
            self.password_input.fill(password)
            
        self.login_button.click()
        
        # The codegen script showed filling a spinbutton after clicking Login
        # We will handle it by waiting for it to appear
        try:
            if pin and self.spin_button.is_visible(timeout=3000):
                self.spin_button.fill(pin)
        except Exception:
            pass # Spin button might solely exist for specific auth layers

    def get_error_message(self):
        try:
            # Wait briefly to catch invalid error validations
            self.error_message.first.wait_for(state="visible", timeout=3000)
            return self.error_message.first.inner_text()
        except:
            return ""
